apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gitops
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/cletus-mangu-amalitech/k8s-lab-gitops.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-demo

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

    syncOptions:
    - CreateNamespace=true
