apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>DevOps GitOps Lab</title>
    </head>
    <body>
      <h1>Hello from Kubernetes!</h1>
      <h2>NGINX deployed using Argo CD</h2>
      <p>Project 1: Kind + Kubernetes + GitHub + Argo CD</p>
    </body>
    </html>
